### PR TITLE
Clicking outside dialog will dimiss dialog (cancel) if configured

### PR DESCRIPTION
**Pull request by hjortzen**
Clicking outside dialog main area closes the dialog, if configured. Updated examples and README.md

Add the option clickOutsideCloses: true to your options when initialising the dialog. Any clicks outside the dialog will dismiss the dialog. 

`this.$dialog.confirm(trans('messages.basic'), {
                    clickOutsideCloses: true
                })`

**Technical change**: Click listener on the container div that closes (if configured) and a stopping propagation of clicks originating from the main-content area to prevent clicks within the main area to accidentally dismiss the dialog.

### CODE REVIEW

**Comment by Godofbrowser** [comment]
@hjortzen Nicely done. Thanks

Can we make the option key `clickOutsideCloses` too a bit shorter and more precise? i was thinking of something like `backdropClick` or `backdropClose`. This also defines it more than a click outside as a click outside would mean anything on the document outside the dialog window. My thoughts though... What do you think?

Thanks once again.

**Comment by hjortzen** [comment]
@Godofbrowser: Sounds like a plan. I always name things verbose and long, seems like I don't have the knack for coming up with condensed names :)

I'll just make those changes in my branch and do another PR? (Newbie GH user)

**Comment by hjortzen** [comment]
Ah, new commits are automatically included in the same PR, I see.
Changed the key and went with the backdropClose-option.

**Comment by Godofbrowser** [comment]
No, changes would be updated. There's a discussion [here](https://stackoverflow.com/questions/7947322/preferred-github-workflow-for-updating-a-pull-request-after-code-review) which might be helpful as it gives more detail.

**Comment by Godofbrowser** [comment]
Yeah 😄 . Merging... Thanks.

**Pull request merged**
